title: looping-sprites
hero_image: images/banner.png
description: looping-sprites description
version: 4
listed: false
copyedit: false
last_tested: "2020-06-30"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
